from collections import OrderedDict
import getpass
import json

username = raw_input('Username: ')
password = getpass.getpass('Password: ')

check_pages_init = 0 # if negative, check all
check_pages = 1

check_buy_items_init = True
check_buy_items      = True

intersperse_buy_items = 1
intersperse_buy_items_pages = 1

check_sets = False

buy_item_if_not_sellable = False

auto_buy = 3 # Cheapest item is 5 (and they're shit, we only want to buy items with the price set accidentally too cheap)

worst_profit_margin = 1.1 # most sold items, interpolated by total_circulation's rank
best_profit_margin  = 1.3 # least sold items

#test_run = True

# Fish says bumping won't work anymore, but it does
# Maybe it only bumps if the item is the cheapest of its kind on the market
bump = 900

buy_items = {
    'Dread Tail':     3000,
    'Mayan Warrior':  5000,
    'Eye Patch':      6000,
    'Green Hat':      10000,
    'Shutter Shades': 10000,
    'Headphones':     10000,
    'Red Submarine':  10000,

    'Tori Hair':              750,
    'Uke Hair':               750,
    'Santa Hat':              3000,
    'Santa Beard':            5000,
    'Candy Locks':            12000,
    #'Cat Ears':               50000,
    #'Centurion':              100000,
    'Daimyo Hat and Scarf':   7000,
    #"Gentleman's Essentials": 25000,
    #'Kung Fu Master Beard':   100000,
    'Minihawk':               4000,
    'Mohawk Hair':            12000,
    'Pony Tail':              12000,
    #'Spiky Hair':             25000,
    "Surfer's Seishin":       10000,
    "The Sultan's Fez":       10000,

    #'DQ Sound':    12000,
    'Grip Sound':  3000,
    'Hit 1 Sound': 600,
    'Hit 2 Sound': 600,
    'Hit 3 Sound': 600,
    'Hit 4 Sound': 600,
    'Hit 5 Sound': 600,
    'Kiai Sound':  800,
    #'Win Sound':   25000,

    'Head Avatar':            1200,
    'Music':                  90,
    #'Set':                    10,
    'Flame Particle Texture': 7000,

    'Dead Soul':         2000,
    'Living Soul':       5000,
    #'Contact KiTFoX':    5000,
    #'Organic Cucumber':  500,
    #'Pickled Cucumbers': 500,
    #'Snowman':           2000,

    'Head Texture':         170,
    'Breast Texture':       1800,
    'Chest Texture':        1800,
    'Groin Texture':        1800,
    'Left Bicep Texture':   1800,
    'Left Foot Texture':    1800,
    'Left Hand Texture':    1800,
    'Left Leg Texture':     1800,
    'Left Pec Texture':     1800,
    'Left Thigh Texture':   1800,
    'Left Tricep Texture':  1800,
    'Right Bicep Texture':  1800,
    'Right Foot Texture':   1800,
    'Right Hand Texture':   1800,
    'Right Leg Texture':    1800,
    'Right Pec Texture':    1800,
    'Right Thigh Texture':  1800,
    'Right Tricep Texture': 1800,
    'Stomach Texture':      1800,

    '256x256 Head Texture':         7500,
    '256x256 Breast Texture':       6000,
    '256x256 Chest Texture':        6000,
    '256x256 Groin Texture':        6000,
    '256x256 Left Bicep Texture':   6000,
    '256x256 Left Foot Texture':    6000,
    '256x256 Left Hand Texture':    6000,
    '256x256 Left Leg Texture':     6000,
    '256x256 Left Pec Texture':     6000,
    '256x256 Left Thigh Texture':   6000,
    '256x256 Left Tricep Texture':  6000,
    '256x256 Right Bicep Texture':  6000,
    '256x256 Right Foot Texture':   6000,
    '256x256 Right Hand Texture':   6000,
    '256x256 Right Leg Texture':    6000,
    '256x256 Right Pec Texture':    6000,
    '256x256 Right Thigh Texture':  6000,
    '256x256 Right Tricep Texture': 6000,
    '256x256 Stomach Texture':      6000,

    '512x512 Head Texture':         18500,
    '512x512 Breast Texture':       15000,
    '512x512 Chest Texture':        15000,
    '512x512 Groin Texture':        15000,
    '512x512 Left Bicep Texture':   15000,
    '512x512 Left Foot Texture':    15000,
    '512x512 Left Hand Texture':    15000,
    '512x512 Left Leg Texture':     15000,
    '512x512 Left Pec Texture':     15000,
    '512x512 Left Thigh Texture':   15000,
    '512x512 Left Tricep Texture':  15000,
    '512x512 Right Bicep Texture':  15000,
    '512x512 Right Foot Texture':   15000,
    '512x512 Right Hand Texture':   15000,
    '512x512 Right Leg Texture':    15000,
    '512x512 Right Pec Texture':    15000,
    '512x512 Right Thigh Texture':  15000,
    '512x512 Right Tricep Texture': 15000,
    '512x512 Stomach Texture':      15000,

    'Abs joint texture':            6000,
    'Left ankle joint texture':     6000,
    'Right ankle joint texture':    6000,
    'Left wrist joint texture':     6000,
    'Right wrist joint texture':    6000,
    'Neck joint texture':           6000,
    'Chest joint texture':          10000,
    'Left elbow joint texture':     10000,
    'Right elbow joint texture':    10000,
    'Left glute joint texture':     10000,
    'Right glute joint texture':    10000,
    'Left hip joint texture':       10000,
    'Right hip joint texture':      10000,
    'Left knee joint texture':      10000,
    'Right knee joint texture':     10000,
    'Left pecs joint texture':      10000,
    'Right pecs joint texture':     10000,
    'Left shoulder joint texture':  10000,
    'Right shoulder joint texture': 10000,
    'Lumbar joint texture':         10000,

    'Left Leg Trail Texture':   3500,
    'Left Hand Trail Texture':  3500,
    'Right Leg Trail Texture':  3500,
    'Right Hand Trail Texture': 3500,

    'Acid Blood':                   2500,
    'Acid Force':                   3000,
    'Acid Relax':                   2000,
    'Acid DQ':                      100,
    'Acid Emote':                   100,
    'Acid Ghost':                   800,
    'Acid Hair':                    500,
    'Acid Timer':                   100,
    'Acid Torso':                   200,
    'Acid User Text':               300,
    'Acid Left Hand Motion Trail':  100,
    'Acid Left Leg Motion Trail':   100,
    'Acid Right Hand Motion Trail': 100,
    'Acid Right Leg Motion Trail':  100,
    'Acid Primary Gradient':        200,
    'Acid Secondary Gradient':      200,

    'Adamantium Blood':                   2000,
    'Adamantium Force':                   3000,
    'Adamantium Relax':                   2000,
    'Adamantium DQ':                      100,
    'Adamantium Emote':                   100,
    'Adamantium Ghost':                   500,
    'Adamantium Hair':                    300,
    'Adamantium Timer':                   100,
    'Adamantium Torso':                   200,
    'Adamantium User Text':               300,
    'Adamantium Left Hand Motion Trail':  100,
    'Adamantium Left Leg Motion Trail':   100,
    'Adamantium Right Hand Motion Trail': 100,
    'Adamantium Right Leg Motion Trail':  100,
    'Adamantium Primary Gradient':        200,
    'Adamantium Secondary Gradient':      200,

    # Not enough qi for Alpha
    # Not enough qi for Amber

    'Amethyst Blood':                   500,
    'Amethyst Force':                   700,
    'Amethyst Relax':                   600,
    'Amethyst DQ':                      60,
    'Amethyst Emote':                   60,
    'Amethyst Ghost':                   200,                                                                                                                                                       
    'Amethyst Hair':                    150,                                                                                                                                                       
    'Amethyst Timer':                   100,                                                                                                                                                       
    'Amethyst Torso':                   150,                                                                                                                                                       
    'Amethyst User Text':               60,                                                                                                                                                        
    'Amethyst Left Hand Motion Trail':  60,                                                                                                                                                        
    'Amethyst Left Leg Motion Trail':   60,                                                                                                                                                        
    'Amethyst Right Hand Motion Trail': 60,                                                                                                                                                        
    'Amethyst Right Leg Motion Trail':  60,                                                                                                                                                        
    'Amethyst Primary Gradient':        120,                                                                                                                                                       
    'Amethyst Secondary Gradient':      120,

    'Aqua Blood':                   500,
    'Aqua Force':                   800,
    'Aqua Relax':                   600,
    'Aqua DQ':                      60,
    'Aqua Emote':                   60,
    'Aqua Ghost':                   200,
    'Aqua Hair':                    120,
    'Aqua Timer':                   80,
    'Aqua Torso':                   150,
    'Aqua User Text':               80,
    'Aqua Left Hand Motion Trail':  60,
    'Aqua Left Leg Motion Trail':   60,
    'Aqua Right Hand Motion Trail': 60,
    'Aqua Right Leg Motion Trail':  60,
    'Aqua Primary Gradient':        180,
    'Aqua Secondary Gradient':      180,

    'Aurora Blood':                   600,
    'Aurora Force':                   3000,
    'Aurora Relax':                   1000,
    'Aurora DQ':                      50,
    'Aurora Emote':                   50,
    'Aurora Ghost':                   400,
    'Aurora Hair':                    800,
    'Aurora Timer':                   30,
    'Aurora Torso':                   400,
    'Aurora User Text':               300,
    'Aurora Left Hand Motion Trail':  50,
    'Aurora Left Leg Motion Trail':   50,
    'Aurora Right Hand Motion Trail': 50,
    'Aurora Right Leg Motion Trail':  50,
    'Aurora Primary Gradient':        50,
    'Aurora Secondary Gradient':      50,

    # Not enough qi for Azurite

    'Beetle Blood':                   300,
    'Beetle Force':                   500,
    'Beetle Relax':                   400,
    'Beetle DQ':                      30,
    'Beetle Emote':                   30,
    'Beetle Ghost':                   50,
    'Beetle Hair':                    100,
    'Beetle Timer':                   30,
    'Beetle Torso':                   50,
    'Beetle User Text':               50,
    'Beetle Left Hand Motion Trail':  30,
    'Beetle Left Leg Motion Trail':   30,
    'Beetle Right Hand Motion Trail': 30,
    'Beetle Right Leg Motion Trail':  30,
    'Beetle Primary Gradient':        30,
    'Beetle Secondary Gradient':      30,

    'Bronze Blood':                   700,
    'Bronze Force':                   1200,
    'Bronze Relax':                   700,
    'Bronze DQ':                      60,
    'Bronze Emote':                   60,
    'Bronze Ghost':                   250,
    'Bronze Hair':                    220,
    'Bronze Timer':                   120,
    'Bronze Torso':                   160,
    'Bronze User Text':               120,
    'Bronze Left Hand Motion Trail':  60,
    'Bronze Left Leg Motion Trail':   60,
    'Bronze Right Hand Motion Trail': 60,
    'Bronze Right Leg Motion Trail':  60,
    'Bronze Primary Gradient':        120,
    'Bronze Secondary Gradient':      120,

    'Camo Blood':                   600,
    'Camo Force':                   1500,
    'Camo Relax':                   800,
    'Camo DQ':                      60,
    'Camo Emote':                   60,
    'Camo Ghost':                   200,
    'Camo Hair':                    300,
    'Camo Timer':                   120,
    'Camo Torso':                   200,
    'Camo User Text':               120,
    'Camo Left Hand Motion Trail':  60,
    'Camo Left Leg Motion Trail':   60,
    'Camo Right Hand Motion Trail': 60,
    'Camo Right Leg Motion Trail':  60,
    'Camo Primary Gradient':        100,
    'Camo Secondary Gradient':      100,
    
    'Chronos Blood':                   30,
    'Chronos Force':                   50,
    'Chronos Relax':                   35,
    'Chronos DQ':                      3,
    'Chronos Emote':                   3,
    'Chronos Ghost':                   15,
    'Chronos Hair':                    10,
    'Chronos Timer':                   8,
    'Chronos Torso':                   10,
    'Chronos User Text':               8,
    'Chronos Left Hand Motion Trail':  3,
    'Chronos Left Leg Motion Trail':   3,
    'Chronos Right Hand Motion Trail': 3,
    'Chronos Right Leg Motion Trail':  3,
    'Chronos Primary Gradient':        10,
    'Chronos Secondary Gradient':      10,

    # TODO v

    'Cobra Blood':                   2000,
    'Cobra Force':                   4000,
    'Cobra Relax':                   2000,
    'Cobra DQ':                      100,
    'Cobra Emote':                   100,
    'Cobra Ghost':                   300,
    'Cobra Hair':                    900,
    'Cobra Timer':                   200,
    'Cobra Torso':                   300,
    'Cobra User Text':               200,
    'Cobra Left Hand Motion Trail':  100,
    'Cobra Left Leg Motion Trail':   100,
    'Cobra Right Hand Motion Trail': 100,
    'Cobra Right Leg Motion Trail':  100,
    'Cobra Primary Gradient':        200,
    'Cobra Secondary Gradient':      200,

    'Copper Blood':                   1000,
    'Copper Force':                   1500,
    'Copper Relax':                   1400,
    'Copper DQ':                      100,
    'Copper Emote':                   100,
    'Copper Ghost':                   300,
    'Copper Hair':                    900,
    'Copper Timer':                   200,
    'Copper Torso':                   300,
    'Copper User Text':               200,
    'Copper Left Hand Motion Trail':  100,
    'Copper Left Leg Motion Trail':   100,
    'Copper Right Hand Motion Trail': 100,
    'Copper Right Leg Motion Trail':  100,
    'Copper Primary Gradient':        200,
    'Copper Secondary Gradient':      200,

    # Not enough qi for Crimson
    # Not enough qi for Demolition
    # Not enough qi forr Demon

    'Dragon Blood':                   2000,
    'Dragon Force':                   2500,
    'Dragon Relax':                   2000,
    'Dragon DQ':                      100,
    'Dragon Emote':                   100,
    'Dragon Ghost':                   500,
    'Dragon Hair':                    1200,
    'Dragon Timer':                   300,
    'Dragon Torso':                   400,
    'Dragon User Text':               300,
    'Dragon Left Hand Motion Trail':  100,
    'Dragon Left Leg Motion Trail':   100,
    'Dragon Right Hand Motion Trail': 100,
    'Dragon Right Leg Motion Trail':  100,
    'Dragon Primary Gradient':        300,
    'Dragon Secondary Gradient':      300,

    'Ecto Blood':                   400,
    'Ecto Force':                   700,
    'Ecto Relax':                   500,
    'Ecto DQ':                      40,
    'Ecto Emote':                   40,
    'Ecto Ghost':                   200,
    'Ecto Hair':                    150,
    'Ecto Timer':                   100,
    'Ecto Torso':                   100,
    'Ecto User Text':               100,
    'Ecto Left Hand Motion Trail':  40,
    'Ecto Left Leg Motion Trail':   40,
    'Ecto Right Hand Motion Trail': 40,
    'Ecto Right Leg Motion Trail':  40,
    'Ecto Primary Gradient':        120,
    'Ecto Secondary Gradient':      120,

    # Not enough qi for Elf

    'Gaia Blood':                   100,
    'Gaia Force':                   250,
    'Gaia Relax':                   200,
    'Gaia DQ':                      10,
    'Gaia Emote':                   20,
    'Gaia Ghost':                   30,
    'Gaia Hair':                    50,
    'Gaia Timer':                   30,
    'Gaia Torso':                   30,
    'Gaia User Text':               30,
    'Gaia Left Hand Motion Trail':  20,
    'Gaia Left Leg Motion Trail':   20,
    'Gaia Right Hand Motion Trail': 20,
    'Gaia Right Leg Motion Trail':  20,
    'Gaia Primary Gradient':        30,
    'Gaia Secondary Gradient':      30,
    
    
    
    # WRONG PRICES
    
    #'Gladiator Blood':                   100,
    #'Gladiator Force':                   250,
    #'Gladiator Relax':                   200,
    #'Gladiator DQ':                      10,
    #'Gladiator Emote':                   20,
    #'Gladiator Ghost':                   30,
    #'Gladiator Hair':                    50,
    #'Gladiator Timer':                   30,
    #'Gladiator Torso':                   30,
    #'Gladiator User Text':               30,
    #'Gladiator Left Hand Motion Trail':  20,
    #'Gladiator Left Leg Motion Trail':   20,
    #'Gladiator Right Hand Motion Trail': 20,
    #'Gladiator Right Leg Motion Trail':  20,
    #'Gladiator Primary Gradient':        30,
    #'Gladiator Secondary Gradient':      30,

    'Gold Blood':                   2000,
    'Gold Force':                   3000,
    'Gold Relax':                   3000,
    'Gold DQ':                      150,
    'Gold Emote':                   150,
    'Gold Ghost':                   400,
    'Gold Hair':                    50,
    'Gold Timer':                   300,
    'Gold Torso':                   500,
    'Gold User Text':               300,
    'Gold Left Hand Motion Trail':  150,
    'Gold Left Leg Motion Trail':   150,
    'Gold Right Hand Motion Trail': 150,
    'Gold Right Leg Motion Trail':  150,
    'Gold Primary Gradient':        300,
    'Gold Secondary Gradient':      300,

    'Helios Blood':                   500,
    'Helios Force':                   600,
    'Helios Relax':                   400,
    'Helios DQ':                      40,
    'Helios Emote':                   40,
    'Helios Ghost':                   200,
    'Helios Hair':                    150,
    'Helios Timer':                   80,
    'Helios Torso':                   120,
    'Helios User Text':               80,
    'Helios Left Hand Motion Trail':  40,
    'Helios Left Leg Motion Trail':   40,
    'Helios Right Hand Motion Trail': 40,
    'Helios Right Leg Motion Trail':  40,
    'Helios Primary Gradient':        120,
    'Helios Secondary Gradient':      120,

    'Hot Pink Blood':                   1000,
    'Hot Pink Force':                   3000,
    'Hot Pink Relax':                   1500,
    'Hot Pink DQ':                      200,
    'Hot Pink Emote':                   200,
    'Hot Pink Ghost':                   400,
    'Hot Pink Hair':                    2000,
    'Hot Pink Timer':                   300,
    'Hot Pink Torso':                   300,
    'Hot Pink User Text':               300,
    'Hot Pink Left Hand Motion Trail':  200,
    'Hot Pink Left Leg Motion Trail':   200,
    'Hot Pink Right Hand Motion Trail': 200,
    'Hot Pink Right Leg Motion Trail':  200,
    'Hot Pink Primary Gradient':        300,
    'Hot Pink Secondary Gradient':      300,

    'Hunter Blood':                   4000,
    'Hunter Force':                   7500,
    'Hunter Relax':                   6000,
    'Hunter DQ':                      400,
    'Hunter Emote':                   400,
    'Hunter Ghost':                   1500,
    'Hunter Hair':                    1000,
    'Hunter Timer':                   800,
    'Hunter Torso':                   800,
    'Hunter User Text':               800,
    'Hunter Left Hand Motion Trail':  400,
    'Hunter Left Leg Motion Trail':   400,
    'Hunter Right Hand Motion Trail': 400,
    'Hunter Right Leg Motion Trail':  400,
    'Hunter Primary Gradient':        800,
    'Hunter Secondary Gradient':      800,

    # Not enough qi for Hydra
    # Not enough qi for Imperial

    'Ivory Blood':                   300,
    'Ivory Force':                   1000,
    'Ivory Relax':                   500,
    'Ivory DQ':                      20,
    'Ivory Emote':                   20,
    'Ivory Ghost':                   100,
    'Ivory Hair Color':              100,
    'Ivory Timer':                   50,
    'Ivory Torso':                   100,
    'Ivory User Text':               50,
    'Ivory Left Hand Motion Trail':  20,
    'Ivory Left Leg Motion Trail':   20,
    'Ivory Right Hand Motion Trail': 20,
    'Ivory Right Leg Motion Trail':  20,
    'Ivory Primary Gradient':        50,
    'Ivory Secondary Gradient':      50,

    'Juryo Blood':                   50,
    'Juryo Force':                   100,
    'Juryo Relax':                   200,
    'Juryo DQ':                      10,
    'Juryo Emote':                   10,
    'Juryo Ghost':                   50,
    'Juryo Hair':                    40,
    'Juryo Timer':                   20,
    'Juryo Torso':                   40,
    'Juryo User Text':               20,
    'Juryo Left Hand Motion Trail':  10,
    'Juryo Left Leg Motion Trail':   10,
    'Juryo Right Hand Motion Trail': 10,
    'Juryo Right Leg Motion Trail':  10,
    'Juryo Primary Gradient':        30,
    'Juryo Secondary Gradient':      30,

    'Kevlar Blood':                   1000,
    'Kevlar Force':                   2000,
    'Kevlar Relax':                   1500,
    'Kevlar DQ':                      100,
    'Kevlar Emote':                   100,
    'Kevlar Ghost':                   500,
    'Kevlar Hair':                    1000,
    'Kevlar Timer':                   300,
    'Kevlar Torso':                   300,
    'Kevlar User Text':               300,
    'Kevlar Left Hand Motion Trail':  100,
    'Kevlar Left Leg Motion Trail':   100,
    'Kevlar Right Hand Motion Trail': 100,
    'Kevlar Right Leg Motion Trail':  100,
    'Kevlar Primary Gradient':        200,
    'Kevlar Secondary Gradient':      200,

    'Knox Blood':                   150,
    'Knox Force':                   250,
    'Knox Relax':                   150,
    'Knox DQ':                      15,
    'Knox Emote':                   15,
    'Knox Ghost':                   75,
    'Knox Hair':                    45,
    'Knox Timer':                   25,
    'Knox Torso':                   45,
    'Knox User Text':               25,
    'Knox Left Hand Motion Trail':  10,
    'Knox Left Leg Motion Trail':   10,
    'Knox Right Hand Motion Trail': 10,
    'Knox Right Leg Motion Trail':  10,
    'Knox Primary Gradient':        40,
    'Knox Secondary Gradient':      40,

    # Not enough qi for Magma
    # Not enough qi for Magnetite

    'Marine Blood':                   350,
    'Marine Force':                   550,
    'Marine Relax':                   500,
    'Marine DQ':                      40,
    'Marine Emote':                   40,
    'Marine Ghost':                   150,
    'Marine Hair':                    150,
    'Marine Timer':                   80,
    'Marine Torso':                   100,
    'Marine User Text':               80,
    'Marine Left Hand Motion Trail':  40,
    'Marine Left Leg Motion Trail':   40,
    'Marine Right Hand Motion Trail': 40,
    'Marine Right Leg Motion Trail':  40,
    'Marine Primary Gradient':        100,
    'Marine Secondary Gradient':      100,

    'Maya Blood':                   500,
    'Maya Force':                   1000,
    'Maya Relax':                   750,
    'Maya DQ':                      50,
    'Maya Emote':                   50,
    'Maya Ghost':                   200,
    'Maya Hair':                    600,
    'Maya Timer':                   100,
    'Maya Torso':                   200,
    'Maya User Text':               150,
    'Maya Left Hand Motion Trail':  50,
    'Maya Left Leg Motion Trail':   50,
    'Maya Right Hand Motion Trail': 50,
    'Maya Right Leg Motion Trail':  50,
    'Maya Primary Gradient':        150,
    'Maya Secondary Gradient':      150,

    # Not enough qi for Mysterio

    'Neptune Blood':                   500,
    'Neptune Force':                   1000,
    'Neptune Relax':                   1000,
    'Neptune DQ':                      80,
    'Neptune Emote':                   80,
    'Neptune Ghost':                   200,
    'Neptune Hair':                    500,
    'Neptune Timer':                   100,
    'Neptune Torso':                   200,
    'Neptune User Text':               80,
    'Neptune Left Hand Motion Trail':  80,
    'Neptune Left Leg Motion Trail':   80,
    'Neptune Right Hand Motion Trail': 80,
    'Neptune Right Leg Motion Trail':  80,
    'Neptune Primary Gradient':        150,
    'Neptune Secondary Gradient':      150,

    # Put Noxious in here
    # Put Old Gold in here

    'Olive Blood':                   500,
    'Olive Force':                   600,
    'Olive Relax':                   500,
    'Olive DQ':                      40,
    'Olive Emote':                   40,
    'Olive Ghost':                   100,
    'Olive Hair':                    100,
    'Olive Timer':                   100,
    'Olive Torso':                   150,
    'Olive User Text':               50,
    'Olive Left Hand Motion Trail':  40,
    'Olive Left Leg Motion Trail':   40,
    'Olive Right Hand Motion Trail': 40,
    'Olive Right Leg Motion Trail':  40,
    'Olive Primary Gradient':        100,
    'Olive Secondary Gradient':      100,

    'Orc Blood':                   50,
    'Orc Force':                   75,
    'Orc Relax':                   50,
    'Orc DQ':                      8,
    'Orc Emote':                   8,
    'Orc Ghost':                   30,
    'Orc Hair':                    20,
    'Orc Timer':                   15,
    'Orc Torso':                   20,
    'Orc User Text':               15,
    'Orc Left Hand Motion Trail':  8,
    'Orc Left Leg Motion Trail':   8,
    'Orc Right Hand Motion Trail': 8,
    'Orc Right Leg Motion Trail':  8,
    'Orc Primary Gradient':        20,
    'Orc Secondary Gradient':      20,

    # Put Persian in here


    # WRONG PRICES

    #'Pharos Blood':                   50,
    #'Pharos Force':                   75,
    #'Pharos Relax':                   50,
    #'Pharos DQ':                      8,
    #'Pharos Emote':                   8,
    #'Pharos Ghost':                   30,
    #'Pharos Hair':                    20,
    #'Pharos Timer':                   15,
    #'Pharos Torso':                   20,
    #'Pharos User Text':               15,
    #'Pharos Left Hand Motion Trail':  8,
    #'Pharos Left Leg Motion Trail':   8,
    #'Pharos Right Hand Motion Trail': 8,
    #'Pharos Right Leg Motion Trail':  8,
    #'Pharos Primary Gradient':        20,
    #'Pharos Secondary Gradient':      20,

    # Not enough qi for Plasma
    # Not enough qi for Platinum
    # Not enough qi for Pure

    # Put Quicksilver in here

    'Radioactive Blood':                   200,
    'Radioactive Force':                   500,
    'Radioactive Relax':                   400,
    'Radioactive DQ':                      30,
    'Radioactive Emote':                   30,
    'Radioactive Ghost':                   50,
    'Radioactive Hair':                    100,
    'Radioactive Timer':                   30,
    'Radioactive Torso':                   50,
    'Radioactive User Text':               50,
    'Radioactive Left Hand Motion Trail':  30,
    'Radioactive Left Leg Motion Trail':   30,
    'Radioactive Right Hand Motion Trail': 30,
    'Radioactive Right Leg Motion Trail':  30,
    'Radioactive Primary Gradient':        30,
    'Radioactive Secondary Gradient':      30,

    # Not enough qi for Raider
    # Not enough qi for Raptor

    # Put Sapphire in here

    # Not enough qi for Shaman

    'Sphinx Blood':                   600,
    'Sphinx Force':                   700,
    'Sphinx Relax':                   600,
    'Sphinx DQ':                      40,
    'Sphinx Emote':                   40,
    'Sphinx Ghost':                   200,
    'Sphinx Hair':                    150,
    'Sphinx Timer':                   80,
    'Sphinx Torso':                   150,
    'Sphinx User Text':               100,
    'Sphinx Left Hand Motion Trail':  50,
    'Sphinx Left Leg Motion Trail':   50,
    'Sphinx Right Hand Motion Trail': 50,
    'Sphinx Right Leg Motion Trail':  50,
    'Sphinx Primary Gradient':        150,
    'Sphinx Secondary Gradient':      150,

    # Not enough qi for Static

    'Superfly Blood':                   200,
    'Superfly Force':                   400,
    'Superfly Relax':                   250,
    'Superfly DQ':                      15,
    'Superfly Emote':                   15,
    'Superfly Ghost':                   100,
    'Superfly Hair':                    75,
    'Superfly Timer':                   45,
    'Superfly Torso':                   45,
    'Superfly User Text':               45,
    'Superfly Left Hand Motion Trail':  20,
    'Superfly Left Leg Motion Trail':   20,
    'Superfly Right Hand Motion Trail': 20,
    'Superfly Right Leg Motion Trail':  20,
    'Superfly Primary Gradient':        40,
    'Superfly Secondary Gradient':      40,

    # Not enough qi for Supernova

    'Titan Blood':                   500,
    'Titan Force':                   1500,
    'Titan Relax':                   1000,
    'Titan DQ':                      50,
    'Titan Emote':                   50,
    'Titan Ghost':                   400,
    'Titan Hair':                    500,
    'Titan Timer':                   75,
    'Titan Torso':                   300,
    'Titan User Text':               100,
    'Titan Left Hand Motion Trail':  50,
    'Titan Left Leg Motion Trail':   50,
    'Titan Right Hand Motion Trail': 50,
    'Titan Right Leg Motion Trail':  50,
    'Titan Primary Gradient':        150,
    'Titan Secondary Gradient':      150,

    'Toxic Blood':                   2500,
    'Toxic Force':                   3500,
    'Toxic Relax':                   2500,
    'Toxic DQ':                      150,
    'Toxic Emote':                   150,
    'Toxic Ghost':                   500,
    'Toxic Hair':                    400,
    'Toxic Timer':                   300,
    'Toxic Torso':                   400,
    'Toxic User Text':               200,
    'Toxic Left Hand Motion Trail':  150,
    'Toxic Left Leg Motion Trail':   150,
    'Toxic Right Hand Motion Trail': 150,
    'Toxic Right Leg Motion Trail':  150,
    'Toxic Primary Gradient':        400,
    'Toxic Secondary Gradient':      400,

    # Put Typhon in here
    # Put Tyrian in here
    # Put Vampire in here
    # Put Velvet in here

    # Not enough qi for Viridian
    # Not enough qi for Void
    # Not enough qi for Vortex

    # Put Vulcan in here

    # Not enough qi for Warrior
}

items = json.load(open('items.json'))

buy_items = OrderedDict(sorted(buy_items.items(), key=lambda d: items[d[0]]['total_circulation'], reverse=True))